IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_User' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_User
  (
	UserID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,SpotifyID NVARCHAR(850) NOT NULL
	,Deleted BIT NOT NULL DEFAULT(0)
	,CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
  )
  CREATE NONCLUSTERED INDEX IX_NC_SpotifyID ON dbo.Spotify_User(SpotifyID);
END
GO