IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_Track' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_Track
  (
	TrackID BIGINT NOT NULL PRIMARY KEY
	,Name NVARCHAR(1000) NOT NULL
	,SpotifyID NVARCHAR(1000) NOT NULL
	,CreatedDate DATETIME NOT NULL DEFAULT(GETUTCDATE())
  )
 
END
GO
