IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_Artist' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_Artist
  (
	ArtistID BIGINT NOT NULL PRIMARY KEY
	,Name NVARCHAR(1000) NOT NULL
  )
END
GO