IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_User' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_User
  (
	UserID BIGINT NOT NULL PRIMARY KEY
	,Name NVARCHAR(1000) NOT NULL
	,CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
  )
	
END
GO