IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_User_Token' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_User_Token
  (
	UserID INT NOT NULL PRIMARY KEY
	,AccessToken NVARCHAR(2000) NOT NULL
	,RefreshToken NVARCHAR(2000) NOT NULL
	,ExpiresIn INT NOT NULL 
	,CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
	,UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE())
	,AccessExpired AS CASE WHEN DATEDIFF(second, CreatedDate, GETDATE()) > ExpiresIn THEN 1 ELSE 0 END
	,FOREIGN KEY(UserID) REFERENCES dbo.Spotify_User(UserID)
  )
END
GO