IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_Track' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_Track
  (
	TrackID INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	,SpotifyID NVARCHAR(850) NOT NULL
	,Name NVARCHAR(1000) NOT NULL
	,CreatedDate DATETIME NOT NULL DEFAULT(GETDATE())
  )
  CREATE NONCLUSTERED INDEX IX_NC_SpotifyID ON dbo.Spotify_Track(SpotifyID);
END
GO