IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES  T
           WHERE T.TABLE_NAME = N'Spotify_User_RefreshToken' AND T.TABLE_SCHEMA = 'dbo' )
BEGIN
  CREATE TABLE dbo.Spotify_User_RefreshToken
  (
	UserID BIGINT NOT NULL PRIMARY KEY
	,Code NVARCHAR(2000) NOT NULL
	,TokenDate DATETIME NOT NULL
	,CreatedDate DATETIME NOT NULL DEFAULT(GETUTCDATE())
	,UpdatedDate DATETIME NOT NULL DEFAULT(GETUTCDATE())
	,FOREIGN KEY(UserID) REFERENCES dbo.Spotify_User(UserID)
  )
END
GO

